### ISSUE TITLE
bak and 48W... file

### ISSUE THREAD

**Issue by DanielRuf** [M4cs/traxss#22]
Are these used or were they automatically created? In the second case they can be probably deleted and added to the .gitignore file.

**Comment by DanielRuf** [comment]
See https://github.com/M4cs/traxss/commit/dbea84bd2d61930fafdda39489105c78cace4e5a

**Comment by M4cs** [comment]
The bak can be removed. the 48W file contains attack vectors.

**Comment by DanielRuf** [comment]
Ok but I see no reference of it in the code so where is it used or referenced / mentioned?
